/*
 * Generated by erpcgen 1.14.0 on Tue Sep 22 16:28:47 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_example_server_h_)
#define _c_example_server_h_

#include "example_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief Communication identifiers */
enum _Communication_ids
{
    kCommunication_service_id = 1,
    kCommunication_Unused_TestRequest_id = 1,
    kCommunication_AppVersion_Get_id = 2,
    kCommunication_Errors_GetAll_id = 3,
    kCommunication_Errors_ClearAll_id = 4,
    kCommunication_ErpcVersion_Get_id = 5,
    kCommunication_Memory_Read_id = 6,
    kCommunication_Memory_Write_id = 7,
    kCommunication_Vesc_SetSpeed_id = 8,
    kCommunication_Vesc_GetSpeedRPM_id = 9,
    kCommunication_Vesc_GetInputCurrent_id = 10,
    kCommunication_Vesc_GetInputVoltage_id = 11,
    kCommunication_Vesc_GetMotorCurrent_id = 12,
    kCommunication_Vesc_GetFETTemp_id = 13,
    kCommunication_Vesc_GetMotorCurrentPositionDeg_id = 14,
    kCommunication_Vesc_GetCurrentDutyCycle_id = 15,
    kCommunication_Vesc_EnableMotorFreespin_id = 16,
    kCommunication_Vesc_ApplyStopCurrent_id = 17,
    kCommunication_AssignVesc_id = 18,
    kCommunication_Move_WithSpeed_id = 19,
    kCommunication_Move_Rotate_id = 20,
    kCommunication_Valve_SetInternalPressure_id = 21,
    kCommunication_Led_SetLevel_id = 22,
};

//! @name Communication
//@{
Erpc_Status_t Unused_TestRequest(uint8_t test_variable);

uint16_t AppVersion_Get(void);

Erpc_Status_t Errors_GetAll(list_Erpc_ErrorInfo_t_1_t * out_errors);

Erpc_Status_t Errors_ClearAll(void);

Erpc_SwVersion_t ErpcVersion_Get(void);

Erpc_Status_t Memory_Read(uint32_t address, uint32_t size, list_uint8_1_t * out_data);

Erpc_Status_t Memory_Write(uint32_t address, const list_uint8_1_t * in_data);

Erpc_Status_t Vesc_SetSpeed(uint32_t rpm, uint8_t controller_id);

int32_t Vesc_GetSpeedRPM(uint8_t controller_id);

int16_t Vesc_GetInputCurrent(uint8_t controller_id);

int16_t Vesc_GetInputVoltage(uint8_t controller_id);

int16_t Vesc_GetMotorCurrent(uint8_t controller_id);

int16_t Vesc_GetFETTemp(uint8_t controller_id);

int16_t Vesc_GetMotorCurrentPositionDeg(uint8_t controller_id);

int16_t Vesc_GetCurrentDutyCycle(uint8_t controller_id);

Erpc_Status_t Vesc_EnableMotorFreespin(uint8_t controller_id);

Erpc_Status_t Vesc_ApplyStopCurrent(uint8_t controller_id, uint32_t stop_current_mA);

Erpc_Status_t AssignVesc(Erpc_VescType_t vesc_type, uint8_t can_id);

Erpc_Status_t Move_WithSpeed(uint8_t speed_percentage, Erpc_MoveType_t move_type);

Erpc_Status_t Move_Rotate(uint8_t rotation_speed_percentage, Erpc_RotateType_t rotation_type);

Erpc_Status_t Valve_SetInternalPressure(uint32_t psi_q15_16);

Erpc_Status_t Led_SetLevel(uint8_t brighness);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return Communication_service service object. */
erpc_service_t create_Communication_service(void);

/*! @brief Destroy Communication_service service object. */
void destroy_Communication_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_example_server_h_
