/*
 * Generated by erpcgen 1.14.0 on Tue Sep 22 16:28:47 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_example_server.h"
#include "example_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class Communication_server: public Communication_interface
{
    public:
        virtual ~Communication_server() {};


        Erpc_Status_t Unused_TestRequest(uint8_t test_variable)
        {
            Erpc_Status_t result;
            result = ::Unused_TestRequest(test_variable);

            return result;
        }

        uint16_t AppVersion_Get(void)
        {
            uint16_t result;
            result = ::AppVersion_Get();

            return result;
        }

        Erpc_Status_t Errors_GetAll(list_Erpc_ErrorInfo_t_1_t * out_errors)
        {
            Erpc_Status_t result;
            result = ::Errors_GetAll(out_errors);

            return result;
        }

        Erpc_Status_t Errors_ClearAll(void)
        {
            Erpc_Status_t result;
            result = ::Errors_ClearAll();

            return result;
        }

        Erpc_SwVersion_t ErpcVersion_Get(void)
        {
            Erpc_SwVersion_t result;
            result = ::ErpcVersion_Get();

            return result;
        }

        Erpc_Status_t Memory_Read(uint32_t address, uint32_t size, list_uint8_1_t * out_data)
        {
            Erpc_Status_t result;
            result = ::Memory_Read(address, size, out_data);

            return result;
        }

        Erpc_Status_t Memory_Write(uint32_t address, const list_uint8_1_t * in_data)
        {
            Erpc_Status_t result;
            result = ::Memory_Write(address, in_data);

            return result;
        }

        Erpc_Status_t Vesc_SetSpeed(uint32_t rpm, uint8_t controller_id)
        {
            Erpc_Status_t result;
            result = ::Vesc_SetSpeed(rpm, controller_id);

            return result;
        }

        int32_t Vesc_GetSpeedRPM(uint8_t controller_id)
        {
            int32_t result;
            result = ::Vesc_GetSpeedRPM(controller_id);

            return result;
        }

        int16_t Vesc_GetInputCurrent(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetInputCurrent(controller_id);

            return result;
        }

        int16_t Vesc_GetInputVoltage(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetInputVoltage(controller_id);

            return result;
        }

        int16_t Vesc_GetMotorCurrent(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetMotorCurrent(controller_id);

            return result;
        }

        int16_t Vesc_GetFETTemp(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetFETTemp(controller_id);

            return result;
        }

        int16_t Vesc_GetMotorCurrentPositionDeg(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetMotorCurrentPositionDeg(controller_id);

            return result;
        }

        int16_t Vesc_GetCurrentDutyCycle(uint8_t controller_id)
        {
            int16_t result;
            result = ::Vesc_GetCurrentDutyCycle(controller_id);

            return result;
        }

        Erpc_Status_t Vesc_EnableMotorFreespin(uint8_t controller_id)
        {
            Erpc_Status_t result;
            result = ::Vesc_EnableMotorFreespin(controller_id);

            return result;
        }

        Erpc_Status_t Vesc_ApplyStopCurrent(uint8_t controller_id, uint32_t stop_current_mA)
        {
            Erpc_Status_t result;
            result = ::Vesc_ApplyStopCurrent(controller_id, stop_current_mA);

            return result;
        }

        Erpc_Status_t AssignVesc(Erpc_VescType_t vesc_type, uint8_t can_id)
        {
            Erpc_Status_t result;
            result = ::AssignVesc(vesc_type, can_id);

            return result;
        }

        Erpc_Status_t Move_WithSpeed(uint8_t speed_percentage, Erpc_MoveType_t move_type)
        {
            Erpc_Status_t result;
            result = ::Move_WithSpeed(speed_percentage, move_type);

            return result;
        }

        Erpc_Status_t Move_Rotate(uint8_t rotation_speed_percentage, Erpc_RotateType_t rotation_type)
        {
            Erpc_Status_t result;
            result = ::Move_Rotate(rotation_speed_percentage, rotation_type);

            return result;
        }

        Erpc_Status_t Valve_SetInternalPressure(uint32_t psi_q15_16)
        {
            Erpc_Status_t result;
            result = ::Valve_SetInternalPressure(psi_q15_16);

            return result;
        }

        Erpc_Status_t Led_SetLevel(uint8_t brighness)
        {
            Erpc_Status_t result;
            result = ::Led_SetLevel(brighness);

            return result;
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(Communication_service, s_Communication_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(Communication_server, s_Communication_server);

erpc_service_t create_Communication_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) Communication_service(new (nothrow)Communication_server());
#else
    if (s_Communication_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_Communication_server.construct();
        s_Communication_service.construct(s_Communication_server.get());
        service = s_Communication_service.get();
    }
#endif

    return service;
}

void destroy_Communication_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (Communication_server *)(((Communication_service *)service)->getHandler());
        delete (Communication_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_Communication_service.get());
    s_Communication_service.destroy();
    s_Communication_server.destroy();
#endif
}

