/*
 * Generated by erpcgen 1.14.0 on Tue Jun  9 20:15:22 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "example_interface.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

Communication_interface::~Communication_interface(void)
{
}
