/*
 * Generated by erpcgen 1.14.0 on Tue Sep 22 16:28:47 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_interface_hpp_)
#define _example_interface_hpp_

#include "example_common.hpp"

namespace erpcShim
{


// Abstract base class for Communication
class Communication_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_Unused_TestRequestId = 1;
        static const uint8_t m_AppVersion_GetId = 2;
        static const uint8_t m_Errors_GetAllId = 3;
        static const uint8_t m_Errors_ClearAllId = 4;
        static const uint8_t m_ErpcVersion_GetId = 5;
        static const uint8_t m_Memory_ReadId = 6;
        static const uint8_t m_Memory_WriteId = 7;
        static const uint8_t m_Vesc_SetSpeedId = 8;
        static const uint8_t m_Vesc_GetSpeedRPMId = 9;
        static const uint8_t m_Vesc_GetInputCurrentId = 10;
        static const uint8_t m_Vesc_GetInputVoltageId = 11;
        static const uint8_t m_Vesc_GetMotorCurrentId = 12;
        static const uint8_t m_Vesc_GetFETTempId = 13;
        static const uint8_t m_Vesc_GetMotorCurrentPositionDegId = 14;
        static const uint8_t m_Vesc_GetCurrentDutyCycleId = 15;
        static const uint8_t m_Vesc_EnableMotorFreespinId = 16;
        static const uint8_t m_Vesc_ApplyStopCurrentId = 17;
        static const uint8_t m_AssignVescId = 18;
        static const uint8_t m_Move_WithSpeedId = 19;
        static const uint8_t m_Move_RotateId = 20;
        static const uint8_t m_Valve_SetInternalPressureId = 21;
        static const uint8_t m_Led_SetLevelId = 22;

        virtual ~Communication_interface(void);

        virtual Erpc_Status_t Unused_TestRequest(uint8_t test_variable) = 0;

        virtual uint16_t AppVersion_Get(void) = 0;

        virtual Erpc_Status_t Errors_GetAll(list_Erpc_ErrorInfo_t_1_t * out_errors) = 0;

        virtual Erpc_Status_t Errors_ClearAll(void) = 0;

        virtual Erpc_SwVersion_t ErpcVersion_Get(void) = 0;

        virtual Erpc_Status_t Memory_Read(uint32_t address, uint32_t size, list_uint8_1_t * out_data) = 0;

        virtual Erpc_Status_t Memory_Write(uint32_t address, const list_uint8_1_t * in_data) = 0;

        virtual Erpc_Status_t Vesc_SetSpeed(uint32_t rpm, uint8_t controller_id) = 0;

        virtual int32_t Vesc_GetSpeedRPM(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetInputCurrent(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetInputVoltage(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetMotorCurrent(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetFETTemp(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetMotorCurrentPositionDeg(uint8_t controller_id) = 0;

        virtual int16_t Vesc_GetCurrentDutyCycle(uint8_t controller_id) = 0;

        virtual Erpc_Status_t Vesc_EnableMotorFreespin(uint8_t controller_id) = 0;

        virtual Erpc_Status_t Vesc_ApplyStopCurrent(uint8_t controller_id, uint32_t stop_current_mA) = 0;

        virtual Erpc_Status_t AssignVesc(Erpc_VescType_t vesc_type, uint8_t can_id) = 0;

        virtual Erpc_Status_t Move_WithSpeed(uint8_t speed_percentage, Erpc_MoveType_t move_type) = 0;

        virtual Erpc_Status_t Move_Rotate(uint8_t rotation_speed_percentage, Erpc_RotateType_t rotation_type) = 0;

        virtual Erpc_Status_t Valve_SetInternalPressure(uint32_t psi_q15_16) = 0;

        virtual Erpc_Status_t Led_SetLevel(uint8_t brighness) = 0;
private:
};
} // erpcShim


#endif // _example_interface_hpp_
