/*
 * Generated by erpcgen 1.14.0 on Sun Jun 28 18:09:21 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "example_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif


//! @brief Function to read struct list_uint8_1_t
static void read_list_uint8_1_t_struct(erpc::Codec * codec, list_uint8_1_t * data);


// Read struct list_uint8_1_t function implementation
static void read_list_uint8_1_t_struct(erpc::Codec * codec, list_uint8_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startReadList(data->elementsCount);
    data->elements = (uint8_t *) erpc_malloc(data->elementsCount * sizeof(uint8_t));
    if ((data->elements == NULL) && (data->elementsCount > 0))
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->read(data->elements[listCount]);
    }
}


//! @brief Function to write struct Erpc_ErrorInfo_t
static void write_Erpc_ErrorInfo_t_struct(erpc::Codec * codec, const Erpc_ErrorInfo_t * data);

//! @brief Function to write struct list_uint8_1_t
static void write_list_uint8_1_t_struct(erpc::Codec * codec, const list_uint8_1_t * data);

//! @brief Function to write struct list_Erpc_ErrorInfo_t_1_t
static void write_list_Erpc_ErrorInfo_t_1_t_struct(erpc::Codec * codec, const list_Erpc_ErrorInfo_t_1_t * data);


// Write struct Erpc_ErrorInfo_t function implementation
static void write_Erpc_ErrorInfo_t_struct(erpc::Codec * codec, const Erpc_ErrorInfo_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->write(static_cast<int32_t>(data->error_id));

    write_list_uint8_1_t_struct(codec, &(data->additional_data));
}

// Write struct list_uint8_1_t function implementation
static void write_list_uint8_1_t_struct(erpc::Codec * codec, const list_uint8_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startWriteList(data->elementsCount);
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->write(data->elements[listCount]);
    }
}

// Write struct list_Erpc_ErrorInfo_t_1_t function implementation
static void write_list_Erpc_ErrorInfo_t_1_t_struct(erpc::Codec * codec, const list_Erpc_ErrorInfo_t_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startWriteList(data->elementsCount);
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        write_Erpc_ErrorInfo_t_struct(codec, &(data->elements[listCount]));
    }
}


//! @brief Function to free space allocated inside struct Erpc_ErrorInfo_t
static void free_Erpc_ErrorInfo_t_struct(Erpc_ErrorInfo_t * data);

//! @brief Function to free space allocated inside struct list_uint8_1_t
static void free_list_uint8_1_t_struct(list_uint8_1_t * data);

//! @brief Function to free space allocated inside struct list_Erpc_ErrorInfo_t_1_t
static void free_list_Erpc_ErrorInfo_t_1_t_struct(list_Erpc_ErrorInfo_t_1_t * data);


// Free space allocated inside struct Erpc_ErrorInfo_t function implementation
static void free_Erpc_ErrorInfo_t_struct(Erpc_ErrorInfo_t * data)
{
    free_list_uint8_1_t_struct(&data->additional_data);
}

// Free space allocated inside struct list_uint8_1_t function implementation
static void free_list_uint8_1_t_struct(list_uint8_1_t * data)
{
    erpc_free(data->elements);
}

// Free space allocated inside struct list_Erpc_ErrorInfo_t_1_t function implementation
static void free_list_Erpc_ErrorInfo_t_1_t_struct(list_Erpc_ErrorInfo_t_1_t * data)
{
    for (uint32_t listCount = 0; listCount < data->elementsCount; ++listCount)
    {
        free_Erpc_ErrorInfo_t_struct(&data->elements[listCount]);
    }

    erpc_free(data->elements);
}



Communication_service::Communication_service(Communication_interface *_Communication_interface)
    : erpc::Service(Communication_interface::m_serviceId)
    , m_handler(_Communication_interface)
{
}

Communication_service::~Communication_service()
{
}

// return service interface handler.
Communication_interface* Communication_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t Communication_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case Communication_interface::m_Unused_TestRequestId:
        {
            erpcStatus = Unused_TestRequest_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_AppVersion_GetId:
        {
            erpcStatus = AppVersion_Get_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Errors_GetAllId:
        {
            erpcStatus = Errors_GetAll_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Errors_ClearAllId:
        {
            erpcStatus = Errors_ClearAll_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_ErpcVersion_GetId:
        {
            erpcStatus = ErpcVersion_Get_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Memory_ReadId:
        {
            erpcStatus = Memory_Read_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Memory_WriteId:
        {
            erpcStatus = Memory_Write_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_SetSpeedId:
        {
            erpcStatus = Vesc_SetSpeed_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetSpeedRPMId:
        {
            erpcStatus = Vesc_GetSpeedRPM_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetInputCurrentId:
        {
            erpcStatus = Vesc_GetInputCurrent_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetInputVoltageId:
        {
            erpcStatus = Vesc_GetInputVoltage_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetMotorCurrentId:
        {
            erpcStatus = Vesc_GetMotorCurrent_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetFETTempId:
        {
            erpcStatus = Vesc_GetFETTemp_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetMotorCurrentPositionDegId:
        {
            erpcStatus = Vesc_GetMotorCurrentPositionDeg_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_GetCurrentDutyCycleId:
        {
            erpcStatus = Vesc_GetCurrentDutyCycle_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_EnableMotorFreespinId:
        {
            erpcStatus = Vesc_EnableMotorFreespin_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case Communication_interface::m_Vesc_ApplyStopCurrentId:
        {
            erpcStatus = Vesc_ApplyStopCurrent_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for Unused_TestRequest of Communication interface.
erpc_status_t Communication_service::Unused_TestRequest_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t test_variable;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(test_variable);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Unused_TestRequest(test_variable);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Unused_TestRequestId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for AppVersion_Get of Communication interface.
erpc_status_t Communication_service::AppVersion_Get_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint16_t result;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->AppVersion_Get();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_AppVersion_GetId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Errors_GetAll of Communication interface.
erpc_status_t Communication_service::Errors_GetAll_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    list_Erpc_ErrorInfo_t_1_t *out_errors = NULL;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    out_errors = (list_Erpc_ErrorInfo_t_1_t *) erpc_malloc(sizeof(list_Erpc_ErrorInfo_t_1_t));
    if (out_errors == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Errors_GetAll(out_errors);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Errors_GetAllId, sequence);

        write_list_Erpc_ErrorInfo_t_1_t_struct(codec, out_errors);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    if (out_errors)
    {
        free_list_Erpc_ErrorInfo_t_1_t_struct(out_errors);
    }
    erpc_free(out_errors);

    return err;
}

// Server shim for Errors_ClearAll of Communication interface.
erpc_status_t Communication_service::Errors_ClearAll_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Errors_ClearAll();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Errors_ClearAllId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for ErpcVersion_Get of Communication interface.
erpc_status_t Communication_service::ErpcVersion_Get_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    Erpc_SwVersion_t result;

    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->ErpcVersion_Get();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_ErpcVersion_GetId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Memory_Read of Communication interface.
erpc_status_t Communication_service::Memory_Read_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint32_t address;
    uint32_t size;
    list_uint8_1_t *out_data = NULL;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(address);

    codec->read(size);

    out_data = (list_uint8_1_t *) erpc_malloc(sizeof(list_uint8_1_t));
    if (out_data == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Memory_Read(address, size, out_data);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Memory_ReadId, sequence);

        write_list_uint8_1_t_struct(codec, out_data);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    if (out_data)
    {
        free_list_uint8_1_t_struct(out_data);
    }
    erpc_free(out_data);

    return err;
}

// Server shim for Memory_Write of Communication interface.
erpc_status_t Communication_service::Memory_Write_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint32_t address;
    list_uint8_1_t *in_data = NULL;
    in_data = (list_uint8_1_t *) erpc_malloc(sizeof(list_uint8_1_t));
    if (in_data == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(address);

    read_list_uint8_1_t_struct(codec, in_data);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Memory_Write(address, in_data);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Memory_WriteId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    if (in_data)
    {
        free_list_uint8_1_t_struct(in_data);
    }
    erpc_free(in_data);

    return err;
}

// Server shim for Vesc_SetSpeed of Communication interface.
erpc_status_t Communication_service::Vesc_SetSpeed_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint32_t rpm;
    uint8_t controller_id;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(rpm);

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_SetSpeed(rpm, controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_SetSpeedId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetSpeedRPM of Communication interface.
erpc_status_t Communication_service::Vesc_GetSpeedRPM_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int32_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetSpeedRPM(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetSpeedRPMId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetInputCurrent of Communication interface.
erpc_status_t Communication_service::Vesc_GetInputCurrent_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetInputCurrent(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetInputCurrentId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetInputVoltage of Communication interface.
erpc_status_t Communication_service::Vesc_GetInputVoltage_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetInputVoltage(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetInputVoltageId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetMotorCurrent of Communication interface.
erpc_status_t Communication_service::Vesc_GetMotorCurrent_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetMotorCurrent(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetMotorCurrentId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetFETTemp of Communication interface.
erpc_status_t Communication_service::Vesc_GetFETTemp_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetFETTemp(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetFETTempId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetMotorCurrentPositionDeg of Communication interface.
erpc_status_t Communication_service::Vesc_GetMotorCurrentPositionDeg_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetMotorCurrentPositionDeg(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetMotorCurrentPositionDegId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_GetCurrentDutyCycle of Communication interface.
erpc_status_t Communication_service::Vesc_GetCurrentDutyCycle_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    int16_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_GetCurrentDutyCycle(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_GetCurrentDutyCycleId, sequence);

        codec->write(result);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_EnableMotorFreespin of Communication interface.
erpc_status_t Communication_service::Vesc_EnableMotorFreespin_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_EnableMotorFreespin(controller_id);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_EnableMotorFreespinId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}

// Server shim for Vesc_ApplyStopCurrent of Communication interface.
erpc_status_t Communication_service::Vesc_ApplyStopCurrent_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t controller_id;
    uint32_t stop_current_mA;
    Erpc_Status_t result;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(controller_id);

    codec->read(stop_current_mA);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->Vesc_ApplyStopCurrent(controller_id, stop_current_mA);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, Communication_interface::m_serviceId, Communication_interface::m_Vesc_ApplyStopCurrentId, sequence);

        codec->write(static_cast<int32_t>(result));

        err = codec->getStatus();
    }

    return err;
}
