/*
 * Generated by erpcgen 1.14.0 on Sun Jun 28 18:09:21 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_client_hpp_)
#define _example_client_hpp_

#include "example_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class Communication_client: public Communication_interface
{
    public:
        Communication_client(erpc::ClientManager *manager);

        virtual ~Communication_client();

        virtual Erpc_Status_t Unused_TestRequest(uint8_t test_variable);

        virtual uint16_t AppVersion_Get(void);

        virtual Erpc_Status_t Errors_GetAll(list_Erpc_ErrorInfo_t_1_t * out_errors);

        virtual Erpc_Status_t Errors_ClearAll(void);

        virtual Erpc_SwVersion_t ErpcVersion_Get(void);

        virtual Erpc_Status_t Memory_Read(uint32_t address, uint32_t size, list_uint8_1_t * out_data);

        virtual Erpc_Status_t Memory_Write(uint32_t address, const list_uint8_1_t * in_data);

        virtual Erpc_Status_t Vesc_SetSpeed(uint32_t rpm, uint8_t controller_id);

        virtual int32_t Vesc_GetSpeedRPM(uint8_t controller_id);

        virtual int16_t Vesc_GetInputCurrent(uint8_t controller_id);

        virtual int16_t Vesc_GetInputVoltage(uint8_t controller_id);

        virtual int16_t Vesc_GetMotorCurrent(uint8_t controller_id);

        virtual int16_t Vesc_GetFETTemp(uint8_t controller_id);

        virtual int16_t Vesc_GetMotorCurrentPositionDeg(uint8_t controller_id);

        virtual int16_t Vesc_GetCurrentDutyCycle(uint8_t controller_id);

        virtual Erpc_Status_t Vesc_EnableMotorFreespin(uint8_t controller_id);

        virtual Erpc_Status_t Vesc_ApplyStopCurrent(uint8_t controller_id, uint32_t stop_current_mA);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _example_client_hpp_
