/*
 * Generated by erpcgen 1.14.0 on Tue Jun  9 20:15:22 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_example_common_hpp_)
#define _example_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_EXAMPLE)
#define ERPC_TYPE_DEFINITIONS_EXAMPLE

// Enumerators data types declarations
typedef enum Erpc_Status_t
{
    ERPC_OK = 0,
    ERPC_NOT_OK = 1
} Erpc_Status_t;

typedef enum Erpc_SwVersion_t
{
    ERPC_INTERFACE_VERSION = 258
} Erpc_SwVersion_t;

typedef enum CanFailedToCreateReason
{
    TaskHandle = 0,
    Can1 = 1,
    Can2 = 2
} CanFailedToCreateReason;

typedef enum Erpc_DetError_t
{
    DET_NO_ERROR = 0,
    DET_UDP_CONNECTION_FAILED_TO_CREATE = 256,
    DET_UDP_SENDING_ERROR = 257,
    DET_SERVER_FAILED_TO_POLL = 512,
    DET_TRANSPORT_LWIP_TCP_CRC_ERROR = 768,
    DET_CAN_FAILED_TO_CREATE = 1024,
    DET_CAN_FAILED_TO_STORE_MESSAGE = 1025,
    DET_CAN_RX_FIFO_FULL_CALLBACK = 1026,
    DET_CAN_ERROR_CALLBACK = 1027,
    DET_CAN_FAILED_TO_CREATE_LISTENER = 1028,
    DET_MALLOC_FAILED_ERPC_SERVER = 65536
} Erpc_DetError_t;

// Aliases data types declarations
typedef struct list_uint8_1_t list_uint8_1_t;
typedef struct CommonErrorData_t CommonErrorData_t;
typedef struct ServerFailedToPoll_t ServerFailedToPoll_t;
typedef struct CanFailedToCreate_t CanFailedToCreate_t;
typedef struct CanFailedToStoreError_t CanFailedToStoreError_t;
typedef struct CanRxFifoFull_t CanRxFifoFull_t;
typedef struct CanErrorCallback_t CanErrorCallback_t;
typedef struct Erpc_ErrorInfo_t Erpc_ErrorInfo_t;
typedef struct list_Erpc_ErrorInfo_t_1_t list_Erpc_ErrorInfo_t_1_t;

// Structures/unions data types declarations
struct list_uint8_1_t
{
    uint8_t * elements;
    uint32_t elementsCount;
};

struct CommonErrorData_t
{
    uint16_t application_sw_version;
    uint16_t erpc_version;
};

struct ServerFailedToPoll_t
{
    uint8_t erpc_status;
};

struct CanFailedToCreate_t
{
    CanFailedToCreateReason reason;
};

struct CanFailedToStoreError_t
{
    uint32_t queue_status;
    uint16_t frame_id;
    uint8_t unique_id;
    uint8_t rx_direction;
};

struct CanRxFifoFull_t
{
    uint8_t can_driver_id;
};

struct CanErrorCallback_t
{
    uint8_t can_driver_id;
    uint32_t error_code;
};

struct Erpc_ErrorInfo_t
{
    Erpc_DetError_t error_id;
    list_uint8_1_t additional_data;
};

struct list_Erpc_ErrorInfo_t_1_t
{
    Erpc_ErrorInfo_t * elements;
    uint32_t elementsCount;
};


#endif // ERPC_TYPE_DEFINITIONS_EXAMPLE


#endif // _example_common_hpp_
