/*
 * Generated by erpcgen 1.14.0 on Tue Sep 22 16:28:47 2026.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include "erpc_port.h"
#endif
#include "erpc_codec.hpp"
#include "example_client.hpp"
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

//! @brief Function to write struct list_uint8_1_t
static void write_list_uint8_1_t_struct(erpc::Codec * codec, const list_uint8_1_t * data);


// Write struct list_uint8_1_t function implementation
static void write_list_uint8_1_t_struct(erpc::Codec * codec, const list_uint8_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startWriteList(data->elementsCount);
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->write(data->elements[listCount]);
    }
}


//! @brief Function to read struct Erpc_ErrorInfo_t
static void read_Erpc_ErrorInfo_t_struct(erpc::Codec * codec, Erpc_ErrorInfo_t * data);

//! @brief Function to read struct list_uint8_1_t
static void read_list_uint8_1_t_struct(erpc::Codec * codec, list_uint8_1_t * data);

//! @brief Function to read struct list_Erpc_ErrorInfo_t_1_t
static void read_list_Erpc_ErrorInfo_t_1_t_struct(erpc::Codec * codec, list_Erpc_ErrorInfo_t_1_t * data);


// Read struct Erpc_ErrorInfo_t function implementation
static void read_Erpc_ErrorInfo_t_struct(erpc::Codec * codec, Erpc_ErrorInfo_t * data)
{
    int32_t _tmp_local_i32;

    if(NULL == data)
    {
        return;
    }

    codec->read(_tmp_local_i32);
    data->error_id = static_cast<Erpc_DetError_t>(_tmp_local_i32);

    read_list_uint8_1_t_struct(codec, &(data->additional_data));
}

// Read struct list_uint8_1_t function implementation
static void read_list_uint8_1_t_struct(erpc::Codec * codec, list_uint8_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startReadList(data->elementsCount);
    data->elements = (uint8_t *) erpc_malloc(data->elementsCount * sizeof(uint8_t));
    if ((data->elements == NULL) && (data->elementsCount > 0))
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->read(data->elements[listCount]);
    }
}

// Read struct list_Erpc_ErrorInfo_t_1_t function implementation
static void read_list_Erpc_ErrorInfo_t_1_t_struct(erpc::Codec * codec, list_Erpc_ErrorInfo_t_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startReadList(data->elementsCount);
    data->elements = (Erpc_ErrorInfo_t *) erpc_malloc(data->elementsCount * sizeof(Erpc_ErrorInfo_t));
    if ((data->elements == NULL) && (data->elementsCount > 0))
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        read_Erpc_ErrorInfo_t_struct(codec, &(data->elements[listCount]));
    }
}




Communication_client::Communication_client(ClientManager *manager)
:m_clientManager(manager)
{
}

Communication_client::~Communication_client()
{
}

// Communication interface Unused_TestRequest function client shim.
Erpc_Status_t Communication_client::Unused_TestRequest(uint8_t test_variable)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Unused_TestRequestId, request.getSequence());

        codec->write(test_variable);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Unused_TestRequestId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface AppVersion_Get function client shim.
uint16_t Communication_client::AppVersion_Get(void)
{
    erpc_status_t err = kErpcStatus_Success;

    uint16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_AppVersion_GetId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_AppVersion_GetId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = 0xFFFFU;
    }

    return result;
}

// Communication interface Errors_GetAll function client shim.
Erpc_Status_t Communication_client::Errors_GetAll(list_Erpc_ErrorInfo_t_1_t * out_errors)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Errors_GetAllId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_list_Erpc_ErrorInfo_t_1_t_struct(codec, out_errors);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Errors_GetAllId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Errors_ClearAll function client shim.
Erpc_Status_t Communication_client::Errors_ClearAll(void)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Errors_ClearAllId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Errors_ClearAllId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface ErpcVersion_Get function client shim.
Erpc_SwVersion_t Communication_client::ErpcVersion_Get(void)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_SwVersion_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_ErpcVersion_GetId, request.getSequence());

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_SwVersion_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_ErpcVersion_GetId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_SwVersion_t) -1;
    }

    return result;
}

// Communication interface Memory_Read function client shim.
Erpc_Status_t Communication_client::Memory_Read(uint32_t address, uint32_t size, list_uint8_1_t * out_data)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Memory_ReadId, request.getSequence());

        codec->write(address);

        codec->write(size);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        read_list_uint8_1_t_struct(codec, out_data);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Memory_ReadId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Memory_Write function client shim.
Erpc_Status_t Communication_client::Memory_Write(uint32_t address, const list_uint8_1_t * in_data)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Memory_WriteId, request.getSequence());

        codec->write(address);

        write_list_uint8_1_t_struct(codec, in_data);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Memory_WriteId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Vesc_SetSpeed function client shim.
Erpc_Status_t Communication_client::Vesc_SetSpeed(uint32_t rpm, uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_SetSpeedId, request.getSequence());

        codec->write(rpm);

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_SetSpeedId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Vesc_GetSpeedRPM function client shim.
int32_t Communication_client::Vesc_GetSpeedRPM(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetSpeedRPMId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetSpeedRPMId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetInputCurrent function client shim.
int16_t Communication_client::Vesc_GetInputCurrent(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetInputCurrentId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetInputCurrentId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetInputVoltage function client shim.
int16_t Communication_client::Vesc_GetInputVoltage(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetInputVoltageId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetInputVoltageId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetMotorCurrent function client shim.
int16_t Communication_client::Vesc_GetMotorCurrent(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetMotorCurrentId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetMotorCurrentId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetFETTemp function client shim.
int16_t Communication_client::Vesc_GetFETTemp(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetFETTempId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetFETTempId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetMotorCurrentPositionDeg function client shim.
int16_t Communication_client::Vesc_GetMotorCurrentPositionDeg(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetMotorCurrentPositionDegId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetMotorCurrentPositionDegId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_GetCurrentDutyCycle function client shim.
int16_t Communication_client::Vesc_GetCurrentDutyCycle(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int16_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_GetCurrentDutyCycleId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_GetCurrentDutyCycleId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = -1;
    }

    return result;
}

// Communication interface Vesc_EnableMotorFreespin function client shim.
Erpc_Status_t Communication_client::Vesc_EnableMotorFreespin(uint8_t controller_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_EnableMotorFreespinId, request.getSequence());

        codec->write(controller_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_EnableMotorFreespinId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Vesc_ApplyStopCurrent function client shim.
Erpc_Status_t Communication_client::Vesc_ApplyStopCurrent(uint8_t controller_id, uint32_t stop_current_mA)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Vesc_ApplyStopCurrentId, request.getSequence());

        codec->write(controller_id);

        codec->write(stop_current_mA);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Vesc_ApplyStopCurrentId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface AssignVesc function client shim.
Erpc_Status_t Communication_client::AssignVesc(Erpc_VescType_t vesc_type, uint8_t can_id)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_AssignVescId, request.getSequence());

        codec->write(static_cast<int32_t>(vesc_type));

        codec->write(can_id);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_AssignVescId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Move_WithSpeed function client shim.
Erpc_Status_t Communication_client::Move_WithSpeed(uint8_t speed_percentage, Erpc_MoveType_t move_type)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Move_WithSpeedId, request.getSequence());

        codec->write(speed_percentage);

        codec->write(static_cast<int32_t>(move_type));

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Move_WithSpeedId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Move_Rotate function client shim.
Erpc_Status_t Communication_client::Move_Rotate(uint8_t rotation_speed_percentage, Erpc_RotateType_t rotation_type)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Move_RotateId, request.getSequence());

        codec->write(rotation_speed_percentage);

        codec->write(static_cast<int32_t>(rotation_type));

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Move_RotateId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Valve_SetInternalPressure function client shim.
Erpc_Status_t Communication_client::Valve_SetInternalPressure(uint32_t psi_q15_16)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Valve_SetInternalPressureId, request.getSequence());

        codec->write(psi_q15_16);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Valve_SetInternalPressureId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}

// Communication interface Led_SetLevel function client shim.
Erpc_Status_t Communication_client::Led_SetLevel(uint8_t brighness)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t _tmp_local_i32;
    Erpc_Status_t result;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_Led_SetLevelId, request.getSequence());

        codec->write(brighness);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        codec->read(_tmp_local_i32);
        result = static_cast<Erpc_Status_t>(_tmp_local_i32);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_Led_SetLevelId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    if (err != kErpcStatus_Success)
    {
        result = (Erpc_Status_t) -1;
    }

    return result;
}
