#pragma once

#include <vector>

#ifdef __cplusplus
extern "C" {
#endif
#include "std_types.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "stm32f4xx_hal.h"
#ifdef __cplusplus
}
#endif


constexpr uint8_t CAN_DATA_SIZE {8U};

typedef struct
{
    uint16_t id;
    uint8_t data[CAN_DATA_SIZE];
    uint8_t data_len;
} CanData_t;

/* Forward declaration for CanListener */
class CanDriverInstance;

class CanListener {
public:
    /* Provide min and max id for the range of messages to be send to this listener. Added driver instance relevant for this listener */
    Std_ReturnType init(uint16_t min_id, uint16_t max_id, CanDriverInstance* driver_instance, TaskHandle_t *task_to_notify);
    /* Used to verify if message to be consumed by this listener */
    bool msgForThisListener(uint16_t id) const;
    /* Puts message from CAN driver directly to message container provided by waitForMsg */
    void storeMsgFromIsr(uint16_t id, const uint8_t *data, uint8_t data_len) const;
    /* Provide container for message to be received. Timeout in ms after which message drop */
    Std_ReturnType waitForMsg(CanData_t& msg, uint32_t timeout=portMAX_DELAY);
private:
    uint16_t m_minId;
    uint16_t m_maxId;
    CanData_t *m_data;
    TaskHandle_t *m_taskToNotify;
};

class CanDriverInstance {
public:
    /* TODO fix this when arguments passing the sizes for FreeRTOS is created */
    CanDriverInstance(uint8_t max_listeners);
    /* Initialize FreeRTOS component of driver (rest HAL init is done by code generated by STM32CubeMX) */
    Std_ReturnType init();
    Std_ReturnType addListener(CanListener *listener);
    void rxMsgDispatcher(CAN_HandleTypeDef *hcan);
    static void taskWrapper(void *pvParameters);
private:
    /* Task executed by FreeRTOS */
    void task();
    /* TODO as a excercise - try to replace the structure with template to check out if this is possible to make this configurable (through the constructor) */
    static constexpr uint32_t m_CAN_STACK_SIZE {256U};
    static constexpr uint32_t m_CAN_TASK_PRIORITY {tskIDLE_PRIORITY + 2};
    StackType_t m_Can_Stack[m_CAN_STACK_SIZE];
    StaticTask_t m_Can_TaskBuffer;
    TaskHandle_t m_Can_TaskHandle = NULL;
    
    static constexpr uint32_t m_CAN_TX_QUEUE_LENGTH {5U};
    static constexpr uint32_t m_CAN_TX_QUEUE_DATA_SIZE {sizeof(CanData_t)};
    StaticQueue_t m_Can_TxQueue;
    uint8_t m_Can_TxQueueStorageArea[m_CAN_TX_QUEUE_LENGTH * m_CAN_TX_QUEUE_DATA_SIZE];
    QueueHandle_t m_Can_QueueHandle;
    // /* Forward declaration - TODO - try to make this configurable */
    // struct freeRTOSData;
    // freeRTOSData* m_rtosData;
    std::vector<CanListener *> m_can_listeners;
};