#define APP_VERSION 0x0100
#define APP_VERSION_SIZEOF (sizeof(uint16_t))

/* Main function for application. This is used to keep whole initialization in autogenerated files from STM32*/
void App_main(void);